name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore test dependencies
      run: dotnet restore TestProject1/TestProject1.csproj

    - name: Build solution
      run: dotnet build TestProject1/TestProject1.csproj --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test TestProject1/TestProject1.csproj --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"
